// Mocks generated by Mockito 5.4.4 from annotations
// in yum_application/test/features/ingredients/data/repositories/ingredient_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:yum_application/src/features/ingredients/data/datasource/remotes/remote_ingredient_api.dart'
    as _i2;
import 'package:yum_application/src/features/ingredients/data/model/ingredient.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteIngredientApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteIngredientApi extends _i1.Mock
    implements _i2.RemoteIngredientApi {
  MockRemoteIngredientApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Ingredient>> getMyIngredient() => (super.noSuchMethod(
        Invocation.method(
          #getMyIngredient,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Ingredient>>.empty(),
      ) as _i3.Stream<List<_i4.Ingredient>>);

  @override
  _i3.Future<_i4.Ingredient> createNewIngredient(_i4.Ingredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewIngredient,
          [ingredient],
        ),
        returnValue:
            _i3.Future<_i4.Ingredient>.value(_i5.dummyValue<_i4.Ingredient>(
          this,
          Invocation.method(
            #createNewIngredient,
            [ingredient],
          ),
        )),
      ) as _i3.Future<_i4.Ingredient>);

  @override
  _i3.Future<void> deleteIngredient(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIngredient,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateIngredient(_i4.Ingredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIngredient,
          [ingredient],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
