// Mocks generated by Mockito 5.4.4 from annotations
// in yum_application/test/features/ingredients/domain/usecases/delete_favorite_category_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yum_application/src/features/ingredients/domain/entities/ingredient_category.dart'
    as _i4;
import 'package:yum_application/src/features/ingredients/domain/repositories/favorite_category_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoriteCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteCategoryRepository extends _i1.Mock
    implements _i2.FavoriteCategoryRepository {
  MockFavoriteCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.IngredientCategory>> getFavorites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i3.Future<List<_i4.IngredientCategory>>.value(
            <_i4.IngredientCategory>[]),
      ) as _i3.Future<List<_i4.IngredientCategory>>);

  @override
  _i3.Future<_i4.IngredientCategory> createFavorite(
          _i4.IngredientCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFavorite,
          [category],
        ),
        returnValue: _i3.Future<_i4.IngredientCategory>.value(
            _i4.IngredientCategory.beef),
      ) as _i3.Future<_i4.IngredientCategory>);

  @override
  _i3.Future<void> deleteFavorite(_i4.IngredientCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFavorite,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
