// Mocks generated by Mockito 5.4.4 from annotations
// in yum_application/test/ingredient/viewModel/ingredient_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yum_application/src/data/ingredient/datasource/remote_datasource.dart'
    as _i2;
import 'package:yum_application/src/data/ingredient/model/ingredient.dart'
    as _i3;
import 'package:yum_application/src/data/ingredient/repository/ingredient_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.RemoteDatasource {
  _FakeRemoteDatasource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIngredient_1 extends _i1.SmartFake implements _i3.Ingredient {
  _FakeIngredient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IngredientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientRepository extends _i1.Mock
    implements _i4.IngredientRepository {
  @override
  _i2.RemoteDatasource get remoteDatasource => (super.noSuchMethod(
        Invocation.getter(#remoteDatasource),
        returnValue: _FakeRemoteDatasource_0(
          this,
          Invocation.getter(#remoteDatasource),
        ),
        returnValueForMissingStub: _FakeRemoteDatasource_0(
          this,
          Invocation.getter(#remoteDatasource),
        ),
      ) as _i2.RemoteDatasource);

  @override
  _i5.Future<List<_i3.Ingredient>> getMyIngredient() => (super.noSuchMethod(
        Invocation.method(
          #getMyIngredient,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Ingredient>>.value(<_i3.Ingredient>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.Ingredient>>.value(<_i3.Ingredient>[]),
      ) as _i5.Future<List<_i3.Ingredient>>);

  @override
  _i5.Future<_i3.Ingredient> createNewIngredient(_i3.Ingredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewIngredient,
          [ingredient],
        ),
        returnValue: _i5.Future<_i3.Ingredient>.value(_FakeIngredient_1(
          this,
          Invocation.method(
            #createNewIngredient,
            [ingredient],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Ingredient>.value(_FakeIngredient_1(
          this,
          Invocation.method(
            #createNewIngredient,
            [ingredient],
          ),
        )),
      ) as _i5.Future<_i3.Ingredient>);
}
