// Mocks generated by Mockito 5.4.4 from annotations
// in yum_application/test/features/ingredients/ui/viewModels/refreginator_ingredient_list_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yum_application/src/features/ingredients/domain/entities/refreginator_ingredient.dart'
    as _i2;
import 'package:yum_application/src/features/ingredients/domain/repositories/ingredient_repository.dart'
    as _i3;
import 'package:yum_application/src/features/ingredients/domain/usecases/create_user_ingredient.dart'
    as _i6;
import 'package:yum_application/src/features/ingredients/domain/usecases/delete_user_ingredient.dart'
    as _i7;
import 'package:yum_application/src/features/ingredients/domain/usecases/get_user_ingredients.dart'
    as _i5;
import 'package:yum_application/src/features/ingredients/domain/usecases/update_user_ingredient.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRefreginatorIngredient_0 extends _i1.SmartFake
    implements _i2.RefreginatorIngredient {
  _FakeRefreginatorIngredient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IngredientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientRepository extends _i1.Mock
    implements _i3.IngredientRepository {
  MockIngredientRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.RefreginatorIngredient>> getMyIngredient() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyIngredient,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.RefreginatorIngredient>>.empty(),
      ) as _i4.Stream<List<_i2.RefreginatorIngredient>>);

  @override
  _i4.Future<_i2.RefreginatorIngredient> createNewIngredient(
          _i2.RefreginatorIngredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewIngredient,
          [ingredient],
        ),
        returnValue: _i4.Future<_i2.RefreginatorIngredient>.value(
            _FakeRefreginatorIngredient_0(
          this,
          Invocation.method(
            #createNewIngredient,
            [ingredient],
          ),
        )),
      ) as _i4.Future<_i2.RefreginatorIngredient>);

  @override
  _i4.Future<void> deleteIngredient(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIngredient,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateIngredient(_i2.RefreginatorIngredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIngredient,
          [ingredient],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetUserIngredients].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserIngredients extends _i1.Mock
    implements _i5.GetUserIngredients {
  MockGetUserIngredients() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.RefreginatorIngredient>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.RefreginatorIngredient>>.empty(),
      ) as _i4.Stream<List<_i2.RefreginatorIngredient>>);
}

/// A class which mocks [CreateUserIngredient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserIngredient extends _i1.Mock
    implements _i6.CreateUserIngredient {
  MockCreateUserIngredient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RefreginatorIngredient> call(
          _i2.RefreginatorIngredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [ingredient],
        ),
        returnValue: _i4.Future<_i2.RefreginatorIngredient>.value(
            _FakeRefreginatorIngredient_0(
          this,
          Invocation.method(
            #call,
            [ingredient],
          ),
        )),
      ) as _i4.Future<_i2.RefreginatorIngredient>);
}

/// A class which mocks [DeleteUserIngredient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUserIngredient extends _i1.Mock
    implements _i7.DeleteUserIngredient {
  MockDeleteUserIngredient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UpdateUserIngredient].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserIngredient extends _i1.Mock
    implements _i8.UpdateUserIngredient {
  MockUpdateUserIngredient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(_i2.RefreginatorIngredient? ingredient) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [ingredient],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
